//#include <ql/termstructures/credit/defaultdensitystructure.hpp>
//#include <ql/termstructures/credit/defaultprobabilityhelpers.hpp>
#include <ql/termstructures/credit/flathazardrate.hpp>
#include <ql/termstructures/credit/hazardratestructure.hpp>
//#include <ql/termstructures/credit/interpolateddefaultdensitycurve.hpp>
//#include <ql/termstructures/credit/interpolatedhazardratecurve.hpp>
//#include <ql/termstructures/credit/interpolatedsurvivalprobabilitycurve.hpp>
//#include <ql/termstructures/credit/piecewisedefaultcurve.hpp>
//#include <ql/termstructures/credit/probabilitytraits.hpp>
//#include <ql/termstructures/credit/survivalprobabilitystructure.hpp>